name: octopus-app
services:
  - name: frontend
    github:
      repo: mahir22B/Info
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile
    source_dir: /
    http_port: 80
    routes:
      - path: /

  - name: backend
    github:
      repo: mahir22B/Info
      branch: main
      deploy_on_push: true
    dockerfile_path: BE/Dockerfile
    source_dir: BE/
    http_port: 5000
    routes:
      - path: /api