name: CI/CD Pipeline for React + Flask 
on:
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # Set up SSH using the private key from GitHub Secrets
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
      # - name: Copy Files to old-build
      #   run: |
      #     ssh -o StrictHostKeyChecking=no javeddevops0@34.130.29.74 << 'EOF'
      #     # Navigate to the /var/www directory
      #     cd /var/www
      #     sudo mkdir -p old-build
      #     sudo cp -r main/* old-build/
      #     sudo ls old-build/
      #     EOF

      - name: Deploy to GCP
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/github-actions-deploy-key javeddevops0@34.130.29.74 << 'EOF'
          # Change directory to /var/www
          cd /var/www
      
          # Ensure correct ownership and permissions for old-build-1 directory
          sudo chown -R javeddevops0:javeddevops0 old-build-1
          sudo chmod -R 755 old-build-1
      
          # Navigate to old-build-1
          cd old-build-1
      
          # Clone the repository using Personal Access Token (PAT)
          if [ ! -d "Info" ]; then
            git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Hassan-DevOps2/Info.git
          fi
      
          # Change to the cloned directory
          cd Info
      
          # List the contents of the Info directory (optional)
          ls -l
          EOF
        env:
          SSH_AUTH_SOCK: /tmp/ssh-XXXXXXAkTsK2/agent.1559
          SSH_AGENT_PID: 1560


