name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies and build
      run: |
        cd src
        npm ci
        npm run build
        cd ..

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SERVER_SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Deploy to DigitalOcean
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
      run: |
        # Copy build files to droplet
        scp -r src/build/* $USERNAME@$HOST:/var/www/myapp/

        ssh $USERNAME@$HOST << EOF
          # Navigate to your project directory
          cd /root/Info

          # Pull the latest changes
          git pull origin main

          # Set up and use Python virtual environment
          python3 -m venv venv
          source venv/bin/activate

          # Install backend dependencies
          cd BE
          pip install -r requirements.txt
          pip install flask gunicorn
          cd ..

          # Set up Gunicorn service if it doesn't exist
          if [ ! -f "/etc/systemd/system/gunicorn.service" ]; then
            sudo tee /etc/systemd/system/gunicorn.service > /dev/null <<EOT
          [Unit]
          Description=Gunicorn instance to serve your Flask application
          After=network.target

          [Service]
          User=root
          WorkingDirectory=/root/Info/BE
          ExecStart=/root/Info/venv/bin/gunicorn --workers 3 --bind unix:app.sock -m 007 app:app

          [Install]
          WantedBy=multi-user.target
          EOT
            sudo systemctl daemon-reload
          fi

          # Restart Gunicorn
          sudo systemctl restart gunicorn

          # Restart Nginx
          sudo systemctl restart nginx

          echo "Deployment completed. Gunicorn and Nginx restarted."

          # Display recent log entries
          echo "Recent Nginx error log entries:"
          sudo tail -n 20 /var/log/nginx/error.log

          echo "Recent API error log entries:"
          sudo tail -n 20 /var/log/nginx/api_error.log

          # List files in the deployment directory
          echo "Files in /var/www/myapp:"
          ls -l /var/www/myapp/
        EOF