name: CI/CD Pipeline for React + Flask 
on:
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # Set up SSH using the private key from GitHub Secrets
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}

      - name: Deploy to GCP
        run: |
          ssh -o StrictHostKeyChecking=no root@34.130.29.74 << 'EOF'
          cd /var/www/main
          git clone https://x-access-token:${{ secrets.TOKEN }}@github.com/Hassan-DevOps2/Info.git .
          # npm install
          # npm run build
          # cd ../BE
          # source venv/bin/activate
          # pip install -r requirements.txt
          # pip install gunicorn psycopg2          
          EOF
