name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SERVER_SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Deploy to DigitalOcean
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
      run: |
        ssh $USERNAME@$HOST << EOF
          set -e  # Exit immediately if a command exits with a non-zero status

          echo "Navigating to /root/Info"
          cd /root/Info

          echo "Pulling latest changes"
          git fetch origin main
          git reset --hard origin/main

          echo "Ensuring python3-venv is installed"
          sudo apt-get update && sudo apt-get install python3-venv -y

          echo "Navigating to BE directory"
          cd BE

          echo "Setting up virtual environment"
          python3 -m venv venv
          source venv/bin/activate

          echo "Creating new requirements file with compatible versions"
          cat << EOT > requirements_compatible.txt
          httpx==0.23.0
          anthropic==0.31.2
          jupyterlab==4.2.1
          openai==1.17.0
          postgrest==0.16.2
          postgrest-py==0.4.0
          # Add other dependencies from your original requirements.txt, 
          # but make sure to use compatible versions
          EOT

          echo "Installing Python dependencies"
          pip install -r requirements_compatible.txt
          pip install flask gunicorn

          echo "Building frontend assets"
          cd ../src
          npm install
          npm run build

          echo "Starting/restarting Gunicorn"
          cd ../BE
          pkill gunicorn || true
          nohup venv/bin/gunicorn --bind 0.0.0.0:8000 app:app > gunicorn.log 2>&1 &
          echo "Gunicorn started. Check gunicorn.log for output."

          deactivate

          echo "Deployment completed"
        EOF