name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SERVER_SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Deploy to DigitalOcean
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
      run: |
        ssh $USERNAME@$HOST << EOF
          cd /root/Info
          git pull origin main
          # Install dependencies
          pip install -r requirements.txt
          pip install flask gunicorn  # Ensure Flask and Gunicorn are installed
          # Build frontend assets (if needed)
          cd src
          npm install
          npm run build
          cd ..
          # Start or restart Gunicorn
          pkill gunicorn || true  # Kill any running Gunicorn processes
          cd BE
          nohup gunicorn --bind 0.0.0.0:8000 app:app > gunicorn.log 2>&1 &
          echo "Gunicorn started. Check gunicorn.log for output."
        EOF