name: CI/CD Pipeline for React + Flask 
on:
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # Set up SSH using the private key from GitHub Secrets
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}

      - name: Deploy to GCP
        run: |
          ssh -o StrictHostKeyChecking=no root@34.130.29.74 << 'EOF'
          cd /var/www
          rm -rf main/* main/.* 2>/dev/null || true
          cd /var/www/main
          git pull https://x-access-token:${{ secrets.TOKEN }}@github.com/Hassan-DevOps2/Info.git
          npm install
          npm run build
          cd /var/www/main/BE
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install gunicorn psycopg2
          fuser -k 5000/tcp || true
          nohup gunicorn --bind 0.0.0.0:5000 --certfile=/etc/letsencrypt/live/instagraphix.pro/fullchain.pem --keyfile=/etc/letsencrypt/live/instagraphix.pro/privkey.pem app:app &
          lsof -i :5000
          EOF
