name: CI/CD Pipeline for React + Flask 
on:
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # Set up SSH using the private key from GitHub Secrets
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
      # - name: Copy Files to old-build
      #   run: |
      #     ssh -o StrictHostKeyChecking=no javeddevops0@34.130.29.74 << 'EOF'
      #     # Navigate to the /var/www directory
      #     cd /var/www
      #     sudo mkdir -p old-build
      #     sudo cp -r main/* old-build/
      #     sudo ls old-build/
      #     EOF

      - name: Deploy to GCP
        run: |
          ssh -o StrictHostKeyChecking=no root@34.130.29.74 << 'EOF'
          # Navigate to the /var/www directory
          cd /var/www
        
          # Remove old-build-1 directory if it exists
          if [ -d "old-build-1" ]; then
            rm -rf old-build-1
          fi
        
          # Create a new directory for cloning the repo
          mkdir old-build-1
          cd old-build-1
        
          # Clone the repository using the root user and Personal Access Token (PAT)
          git clone https://x-access-token:${{ secrets.TOKEN }}@github.com/Hassan-DevOps2/Info.git .
        
          # List the contents to verify the repo was cloned
          ls -l
          EOF
        env:
          SSH_AUTH_SOCK: /tmp/ssh-XXXXXXAkTsK2/agent.1559
          SSH_AGENT_PID: 1560

