name: CI/CD Pipeline for React + Flask 
on:
  workflow_dispatch:


jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Adjust according to your Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r BE/requirements.txt

      - name: Deploy Backend to GCP
        run: |
          # SSH into your GCP Compute Engine instance
          ssh -o StrictHostKeyChecking=no ${{ secrets.GCP_SSH_USER }}@${{ secrets.GCP_SSH_HOST }} << EOF
            cd /path/to/your/backend
            git pull origin main
            source venv/bin/activate  # Activate your virtual environment
            pip install -r requirements.txt  # Install any updated requirements
            systemctl restart your-backend-service  # Restart your Flask service
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GCP_SSH_PRIVATE_KEY }}

  frontend:
    runs-on: ubuntu-latest
    needs: backend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install Dependencies
        run: npm install
        working-directory: ./src

      - name: Build React App
        run: npm run build
        working-directory: ./src

      - name: Deploy Frontend to GCP
        run: |
          # SSH into your GCP Compute Engine instance
          ssh -o StrictHostKeyChecking=no ${{ secrets.GCP_SSH_USER }}@${{ secrets.GCP_SSH_HOST }} << EOF
            cd /path/to/your/frontend
            git pull origin main
            npm install  # Install any updated dependencies
            npm run build  # Build the frontend
            sudo cp -r build/* /var/www/html  # Copy the build to the web server directory
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
