name: CI/CD Pipeline for React + Flask 
on:
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # Set up SSH using the private key from GitHub Secrets
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
      # - name: Copy Files to old-build
      #   run: |
      #     ssh -o StrictHostKeyChecking=no javeddevops0@34.130.29.74 << 'EOF'
      #     # Navigate to the /var/www directory
      #     cd /var/www
      #     sudo mkdir -p old-build
      #     sudo cp -r main/* old-build/
      #     sudo ls old-build/
      #     EOF

      - name: Deploy to GCP
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/github-actions-deploy-key javeddevops0@34.130.29.74 << 'EOF'
          cd /var/www/old-build-1
          if [ ! -d ".git" ]; then
            sudo git clone https://github.com/Hassan-DevOps2/Info.git .
          fi
          sudo git pull origin main
          ls /var/www/old-build-1
          EOF


