name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SERVER_SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Deploy to DigitalOcean
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
      run: |
        ssh $USERNAME@$HOST << EOF
          cd /root/Info
          git pull origin main
          
          # Install backend dependencies
          pip install -r requirements.txt
          pip install flask gunicorn
          
          # Build frontend assets
          npm install
          npm run build
          
          # Copy built frontend assets to the correct location
          cp -r build/* /var/www/html/  # Adjust this path as needed
          
          # Restart Gunicorn
          sudo systemctl restart gunicorn
          
          # Restart Nginx (if you're using it)
          sudo systemctl restart nginx
          
          echo "Deployment completed. Gunicorn and Nginx restarted."
        EOF