name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SERVER_SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Deploy to DigitalOcean
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
      run: |
        ssh $USERNAME@$HOST << EOF
          # Navigate to your project directory
          cd /root/Info

          # Pull the latest changes
          git pull origin main

          # Install backend dependencies
          pip install -r requirements.txt
          pip install flask gunicorn

          # Navigate to the frontend directory
          cd src

          # Install frontend dependencies and build
          npm install
          npm run build

          # Copy built frontend assets to the Nginx root directory
          sudo cp -r build/* /var/www/myapp/

          # Navigate back to the project root
          cd ..

          # Restart Gunicorn
          # Assuming you have a systemd service for Gunicorn
          sudo systemctl restart gunicorn

          # Restart Nginx
          sudo systemctl restart nginx

          # Optional: Check if services are running
          echo "Checking Gunicorn status:"
          sudo systemctl status gunicorn
          
          echo "Checking Nginx status:"
          sudo systemctl status nginx

          echo "Deployment completed. Gunicorn and Nginx restarted."

          # Optional: Display recent log entries
          echo "Recent Nginx error log entries:"
          sudo tail -n 20 /var/log/nginx/error.log

          echo "Recent API error log entries:"
          sudo tail -n 20 /var/log/nginx/api_error.log

          # Optional: List files in the deployment directory
          echo "Files in /var/www/myapp:"
          ls -l /var/www/myapp/
        EOF